---
- name: playbook to run Bash scripts
  hosts: all
  become: true
  tasks:
  - name: run script to show users and lat login time
    ansible.builtin.script: users.sh

  - name: run script to show running and stopped services
    ansible.builtin.script: services.sh
