---
- name: playbook to run powershell scripts
  hosts: windows
  tasks:
  - name: run powershell script to show users
    ansible.windows.win_shell: win_users.ps1

  - name: run powershell script to show services
    ansible.windows.win_shell: win_services.ps1
