---
- name: playbook to run powershell scripts
  hosts: windows
  gather_facts: false
  tasks:
  - name: Copy powershell file
    ansible.windows.win_copy:
      src: "{{ item }}"
      dest: C:\Temp\
    loop:
      - win_users_services.ps1
      
  - name: run powershell script
    ansible.windows.win_shell: C:\Temp\win_users_services.ps1 "{{ win_argument }}"
    changed_when: False
