---
- name: playbook to run powershell scripts
  hosts: windows
  gather_facts: false
  tasks:
  - name: Copy a single file keeping the filename
    ansible.windows.win_copy:
      src: "{{ item }}"
      dest: C:\Temp\
    loop:
      - files\win_users.ps1
      - files\win_services.ps1
      
  - name: run powershell script to show users
    ansible.windows.win_shell: C:\Temp\win_users.ps1

  - name: run powershell script to show services
    ansible.windows.win_shell: C:\Temp\win_services.ps1
